### ISSUE TITLE
Data processing performance needs to be improved

### ISSUE THREAD

**Issue by sfluegel05** [ChEB-AI/python-chebai#32]
Data preprocessing is currently not as efficient as it could / should be. On my machine, it took several minutes to create a new dataset (for ChEBI version 231). Large parts of that went into the creation of data splits.

While most of this is not a problem since datasets can be reused between training runs, after adding dynamic datasplits in PR #29, the split creation is repeated at the start of each run. 

## Tasks
- find out which steps of the preprocessing take up the most time
- if possible, find more efficient solutions for steps that are currently inefficient

**Comment by aditya0by0** [comment]
Hi @sfluegel05 
After profiling the preprocessing step, it is clear that the majority of the time is spent in the `split` function of `MultilabelStratifiedShuffleSplit`, which is part of a standard imported library.

I have attached the `.pstat` file generated by applying cProfile to our code for your reference: [dynamic_split_cprofiler_stats.zip](https://github.com/user-attachments/files/15904484/dynamic_split_cprofiler_stats.zip)


Given that the time-consuming part is within a standard library function, I am currently unable to think of a direct approach to optimize it further for performance. 

I would appreciate any further insights or suggestions you might have regarding this performance issue.

**Statistics**, filtered by time required in decreasing order:
![iterative_cprofile_stats](https://github.com/ChEB-AI/python-chebai/assets/65857172/bebce5dd-ceae-408b-a161-cdfdd9465b67)

**Call Graph**:
![iterative_cprofile_call_graph](https://github.com/ChEB-AI/python-chebai/assets/65857172/b109806f-7842-4178-a170-ec8d37ff3ba3)

**Comment by sfluegel05** [comment]
In that case, I'm afraid there is not much we can do regarding the data splits.
Could you have a look at the whole preprocessing pipeline as well? Maybe there are some other steps we can optimise.

**Comment by sfluegel05** [comment]
I tried replacing the `iterative_stratification` package with [`scikit-multilearn`](http://scikit.ml/api/skmultilearn.model_selection.iterative_stratification.html#skmultilearn.model_selection.iterative_stratification.iterative_train_test_split). But apparently, that implementation is less efficient than `iterative_stratification` (although the algorithm is the same).

**Comment by sfluegel05** [comment]
I agree that this makes sense. I don't see how this is connected to the issue however. Could you open a new issue for this and then implement it?

**Comment by sfluegel05** [comment]
We decided that at this point no obvious performance improvements can be made. With the dynamic data split implementation, it is possible to reuse splits and datasets. We recommend doing that to avoid long loading times.
