### ISSUE TITLE
Code needs to be documented

### ISSUE THREAD

**Issue by sfluegel05** [ChEB-AI/python-chebai#9]
# Tasks
- Annotate code with docstrings 
  - as an orientation, use the docstrings used by PyTorch Lightning 
- Where possible, also add type hints to function signatures

Later on: integrate into readthedocs

**Comment by sfluegel05** [comment]
some docstrings have been added in #19

**Comment by sfluegel05** [comment]
There are still missing docstrings for many classes. To improve the coverage, I would suggest to prioritize and leave out some classes that are currently not used. These include 
- models (except for `base` and `electra`)
- datasets with a `JCI` prefix
- files in the `results` folder (except for `utils` and `classification`)

**Comment by aditya0by0** [comment]
Can you please tell me do we need to leave out the classes `ElectraLegacy`, `ConeElectra`, `ConeLoss` in `chebai/models/electra.py`
as it seems they are also not used in anywhere in **configs**

Also all the classes in file `chebai/preprocessing/collect_all.py`

**Comment by sfluegel05** [comment]
You can leave those classes out, as they are (probably) not in use at the moment. We can still document them later when the need arises.
